create /test root
create /test/k1 a
create /test/k2 b
create /test/k3 c
create /test/k4 d
create /test/k5 e
create /test/k6 f
create /test/k7 g
create /test/k8 h
create /test/k9 i
create /test/k10 j
create /test/k11 k
create /test/k12 l
create /test/k13 m
create /test/k14 n
create /test/k15 o
create /test/k16 p
create /test/k17 q
create /test/k18 r
create /test/k19 s
create /test/k20 t
create /test/k21 u
create /test/k22 v
create /test/k23 w
create /test/k24 x
create /test/k25 y
create /test/k26 z
