remove /test/k1
remove /test/k2
remove /test/k3
remove /test/k4
remove /test/k5
remove /test/k6
remove /test/k7
remove /test/k8
remove /test/k9
remove /test/k10
remove /test/k11
remove /test/k12
remove /test/k13
remove /test/k14
remove /test/k15
remove /test/k16
remove /test/k17
remove /test/k18
remove /test/k19
remove /test/k20
remove /test/k21
remove /test/k22
remove /test/k23
remove /test/k24
remove /test/k25
remove /test/k26
remove /test
