remove /test/a
remove /test/b
remove /test/c
remove /test/d
remove /test/e
remove /test/f
remove /test/g
remove /test/h
remove /test/i
remove /test/j
remove /test/k
remove /test/l
remove /test/m
remove /test/n
remove /test/o
remove /test/p
remove /test/q
remove /test/r
remove /test/s
remove /test/t
remove /test/u
remove /test/v
remove /test/w
remove /test/x
remove /test/y
remove /test/z
remove /test
